### ISSUE TITLE
Handle case when there are package dependents, but package itself isn't published to the hackage.haskell.org

### ISSUE THREAD

**Issue by visortelle** [visortelle/hackage-ui#14]
Example of such a package: 

https://hackage-ui.vercel.app/package/rts

<img width="1132" alt="Screen Shot 2022-01-24 at 4 40 55 PM" src="https://user-images.githubusercontent.com/9302460/150814678-e1fda866-43e7-4671-997f-0c4664f37b5e.png">

On hackage.haskell.org:

<img width="1149" alt="Screen Shot 2022-01-24 at 4 41 16 PM" src="https://user-images.githubusercontent.com/9302460/150814745-2690a932-4301-42cc-a124-62a3f16c4e43.png">

**Comment by visortelle** [comment]
Looks like it's not a real package, but still need to handle this situation.

https://www.reddit.com/r/haskell/comments/8t77wi/how_does_the_rts_package_work_how_is_it_related/

https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/rts

**Comment by yutotakano** [comment]
This also happens if I directly use a Git repository and a pinned commit tag as a dependency as well, such as with [my package](https://hackage-ui.vercel.app/package/discord-haskell-voice/dependencies)'s `opus` dependency.

There's not a lot we can do to detect this unfortunately, since the cabal file doesn't indicate anything. Rather, in my package, the Stack build manager is responsible for fetching external dependencies, and I believe Cabal isn't even aware that it's not sourced from Hackage.

Perhaps a 404 is good enough.

**Comment by visortelle** [comment]
@yutotakano yeah. 

404 with a well-descriptive message should be enough.

**Comment by visortelle** [comment]
Fixed in https://github.com/visortelle/hackage-ui/commit/ff2d125c3f459e6834ddb632440276ecd5da7d74

Better looking error pages will implement later.
