### ISSUE TITLE
Haskell Spotlight doesn't open in vs code

### ISSUE THREAD

**Issue by C0d3r-42** [visortelle/hackage-ui#18]
**Describe the bug**
Hello,
when opening Haskell Spotlight in VS Code (e.g. with ALT + 'H'), the tab opens, but it is blank.
The Output-Frame of VS Code shows nothing but "Get once".

**To Reproduce**
1. Go to VS Code
2. Press ALT + 'H' or open Haskell Spotlight
3. Open Output of Haskell Spotlight

**Screenshots**

![image](https://user-images.githubusercontent.com/118287308/202107384-81ce3951-8f71-48b3-a806-e69202b04e44.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 running a Remote Desktop within VSCode running a debian within WSL 2 (`Linux abceefe7d034 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux`) 

**Additional context**
 - works from outside the remote container

**Comment by visortelle** [comment]
@C0d3r-42 hi. Thank you for the bug report.

Quick googling shows many WSL-related bugs with VSCode extensions that use WebView.

For example:
https://github.com/microsoft/vscode/issues/105536
https://github.com/gitkraken/vscode-gitlens/issues/1172

I think the bug is out of the scope of the haskell-spotlight extension itself.
